FROM alpine:latest
CMD echo "+-----------------------------------------+"\
&& echo "|   UNIVERSIDAD COOPERATIVA DE COLOMBIA   |"\
&& echo "+-----------------------------------------+"\
&& echo "|               By. Tefa25.               |"\
&& echo "+-----------------------------------------+"