CREATE TABLE ETL.CRIME_LACITY (
	DR_NO NUMBER(15,0),
	DATE_RPTD VARCHAR2(22),
	AREA_NAME VARCHAR2(11),
	CRM_CD_DESC VARCHAR2(56),
	CONSTRAINT CRIME_LACITY_PK PRIMARY KEY (DR_NO),
	CONSTRAINT SYS_C008645 CHECK ("DR_NO" IS NOT NULL)
);
 CREATE UNIQUE INDEX CRIME_LACITY_PK ON ETL.CRIME_LACITY (DR_NO);
 
SELECT DR_NO, DATE_RPTD, AREA_NAME, CRM_CD_DESC
FROM ETL.CRIME_LACITY;

SELECT COUNT(*)
FROM ETL.CRIME_LACITY;

-- Se crean las tablas que se usarán ORCL-Pentaho

CREATE TABLE ETL.CRIME_LACITY_15A_21C (
	DR_NO NUMBER(15,0),
	DATE_RPTD VARCHAR2(22),
	AREA_NAME VARCHAR2(11),
	CRM_CD_DESC VARCHAR2(56),
	DATE_OCC VARCHAR2(22),
	TIME_OCC NUMBER(15,0),
	AREA NUMBER(15,0),
	RPT_DIST_NO NUMBER(15,0),
	PART_1_2 NUMBER(15,0),
	CRM_CD NUMBER(15,0),
	MOCODES VARCHAR2(49),
	VICT_AGE NUMBER(15,0),
	VICT_SEX VARCHAR2(1),
	VICT_DESCENT VARCHAR2(1),
	PREMIS_CD NUMBER(15,0),
	PREMIS_DESC VARCHAR2(64),
	WEAPON_USED_CD NUMBER(15,0),
	WEAPON_DESC VARCHAR2 (46),
	STATUS VARCHAR2(2),
	STATUS_DESC VARCHAR2(12),
	LOCATION VARCHAR2(40),
	CONSTRAINT CRIME_LACITY_15A_21C PRIMARY KEY (DR_NO),
	CONSTRAINT SYS_C008646 CHECK ("DR_NO" IS NOT NULL)
);


CREATE TABLE ETL.CRIME_LACITY_9A_13C (
	DR_NO NUMBER(15,0),
	DATE_RPTD VARCHAR2(22),
	AREA_NAME VARCHAR2(11),
	CRM_CD_DESC VARCHAR2(56),
	DATE_OCC VARCHAR2(22),
	TIME_OCC NUMBER(15,0),
	AREA NUMBER(15,0),
	RPT_DIST_NO NUMBER(15,0),
	VICT_AGE NUMBER(15,0),
	VICT_SEX VARCHAR2(1),
	PREMIS_DESC VARCHAR2(64),
	WEAPON_USED_CD NUMBER(15,0),
	STATUS VARCHAR2(2),
	CONSTRAINT CRIME_LACITY_9A_13C PRIMARY KEY (DR_NO),
	CONSTRAINT SYS_C008647 CHECK ("DR_NO" IS NOT NULL)
);


SELECT COUNT(*)
FROM ETL.CRIME_LACITY_15A_21C;


SELECT COUNT(*)
FROM ETL.CRIME_LACITY_9A_13C;



